version: "3.8"
services:
  php_docker_starter_template:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5002:80"
    volumes:
      - ./:/var/www/html 
